name: Tag

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
        type: string
      message:
        description: 'Tag message'
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ inputs.version }}
          message: ${{ inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
